import type { Metadata } from "next";
import localFont from "next/font/local";
import React from "react";
import "./globals.css";

const monaSans = localFont({
  src: "../assets/font/Mona-Sans.ttf",
  variable: "--font-mona-sans",
  display: "swap",
});

const sourceSerif = localFont({
  src: "../assets/font/SourceSerif4[opsz,wght].ttf",
  variable: "--font-source-serif",
  display: "swap",
});

const helveticaRounded = localFont({
  src: "../assets/font/helvetica-rounded-bold-5871d05ead8de.otf",
  variable: "--font-helveticaRounded",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${monaSans.variable} ${sourceSerif.variable} ${helveticaRounded.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
